const GLOBAL_FETCH = 'GLOBAL_FETCH';
const GLOBAL_SUCCESS = 'GLOBAL_SUCCESS';
const GLOBAL_ERROR = 'GLOBAL_ERROR';

const TRENDING_FETCH = 'TRENDING_FETCH';
const TRENDING_SUCCESS = 'TRENDING_SUCCESS';
const TRENDING_ERROR = 'TRENDING_ERROR';

const MARKET_FETCH = 'MARKET_FETCH';
const MARKET_SUCCESS = 'MARKET_SUCCESS';
const MARKET_ERROR = 'MARKET_ERROR';

export { 
    GLOBAL_FETCH, 
    GLOBAL_SUCCESS, 
    GLOBAL_ERROR,

    TRENDING_FETCH,
    TRENDING_SUCCESS,
    TRENDING_ERROR,

    MARKET_FETCH,
    MARKET_SUCCESS,
    MARKET_ERROR
}